MODULE = unicoap_driver_gatt

# todo: remove, but set PDU size somewhere else!!

# https://github.com/apache/mynewt-nimble/blob/b0c3e4a085f1a2ed1b4439c04eec423cc7f79661/nimble/host/include/host/ble_att.h#L226
CFLAGS += -DCONFIG_UNICOAP_PDU_SIZE_MAX=512

include $(RIOTBASE)/Makefile.base
